import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/productSchema.js";

dotenv.config();

const products = [
  // =========================
  // DRESSES
  // =========================
  {
    name: "2CL Gown",
    category: "dresses",
    price: 129.99,
    rating: 4.8,
    image: "2clgown.jpg",
    description: "Elegant gown perfect for special occasions.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Blue Gown",
    category: "dresses",
    price: 249.99,
    rating: 4.9,
    image: "bluegown.jpg",
    description: "Beautiful blue gown with an elegant and stylish design.",
    isNew: true,
    isSale: true,
    discount: 30,
    stock: 10,
  },
  {
    name: "Floral Gown",
    category: "dresses",
    price: 99.99,
    rating: 4.7,
    image: "floralgown.jpg",
    description: "Beautiful floral gown for a feminine and elegant look.",
    isNew: false,
    isSale: true,
    discount: 15,
    stock: 10,
  },
  {
    name: "Green Gown",
    category: "dresses",
    price: 189.99,
    rating: 4.8,
    image: "greengown.jpg",
    description: "Elegant green gown perfect for special occasions.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Long Pink Gown",
    category: "dresses",
    price: 79.99,
    rating: 4.6,
    image: "longpinkgown.jpg",
    description: "A beautiful long pink gown with a sophisticated style.",
    isNew: false,
    isSale: true,
    discount: 20,
    stock: 10,
  },
  {
    name: "Multi Gown",
    category: "dresses",
    price: 149.99,
    rating: 4.8,
    image: "multigown.jpg",
    description: "Stylish multi-coloured gown for a bold fashion look.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Pink Gown",
    category: "dresses",
    price: 199.99,
    rating: 4.9,
    image: "pinkgown.jpg",
    description: "Elegant pink gown designed for a beautiful feminine look.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "White Gown",
    category: "dresses",
    price: 159.99,
    rating: 4.9,
    image: "whitegown.jpg",
    description: "Classic white gown with an elegant finish.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Brown Bodycon",
    category: "dresses",
    price: 119.99,
    rating: 4.7,
    image: "brownbodycon.jpg",
    description: "Stylish brown bodycon dress with a flattering fit.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },

  // =========================
  // TOPS
  // =========================
  {
    name: "Brown Top",
    category: "tops",
    price: 89.99,
    rating: 4.7,
    image: "browntop.jpg",
    description: "Simple and stylish brown top.",
    isNew: false,
    isSale: true,
    discount: 10,
    stock: 10,
  },
  {
    name: "Crop Yellow Top",
    category: "tops",
    price: 79.99,
    rating: 4.6,
    image: "cropyellowtop.jpg",
    description: "Trendy crop yellow top for a stylish casual look.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Floral Top",
    category: "tops",
    price: 99.99,
    rating: 4.8,
    image: "flowertop.jpg",
    description: "Beautiful floral top with a feminine design.",
    isNew: false,
    isSale: true,
    discount: 15,
    stock: 10,
  },
  {
    name: "Gathered Top",
    category: "tops",
    price: 109.99,
    rating: 4.8,
    image: "gatheredtop.jpg",
    description: "Elegant gathered top for a sophisticated look.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Pink Top",
    category: "tops",
    price: 89.99,
    rating: 4.7,
    image: "pinktop.jpg",
    description: "Beautiful pink top for everyday elegance.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Sea Green Top",
    category: "tops",
    price: 99.99,
    rating: 4.8,
    image: "seagreentop.jpg",
    description: "Fresh sea green top with a stylish finish.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "White Top",
    category: "tops",
    price: 79.99,
    rating: 4.6,
    image: "whitetop.jpg",
    description: "Classic white top that pairs beautifully with any outfit.",
    isNew: false,
    isSale: true,
    discount: 10,
    stock: 10,
  },
  {
    name: "Yellow Top",
    category: "tops",
    price: 89.99,
    rating: 4.7,
    image: "yellow2top.jpg",
    description: "Bright yellow top for a stylish and confident look.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },

  // =========================
  // BOTTOMS
  // =========================
  {
    name: "Blue Skirt",
    category: "bottoms",
    price: 89.99,
    rating: 4.7,
    image: "blueskirt.jpg",
    description: "Stylish blue skirt perfect for different occasions.",
    isNew: false,
    isSale: true,
    discount: 15,
    stock: 10,
  },
  {
    name: "Floral Skirt",
    category: "bottoms",
    price: 99.99,
    rating: 4.8,
    image: "floralskirt.jpg",
    description: "Beautiful floral skirt with a feminine finish.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Brown Pants",
    category: "bottoms",
    price: 109.99,
    rating: 4.8,
    image: "brownpants.jpg",
    description: "Elegant brown pants for a sophisticated look.",
    isNew: false,
    isSale: true,
    discount: 10,
    stock: 10,
  },
  {
    name: "Jean",
    category: "bottoms",
    price: 119.99,
    rating: 4.7,
    image: "jean.jpg",
    description: "Classic jeans designed for everyday comfort and style.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Satin Skirt",
    category: "bottoms",
    price: 129.99,
    rating: 4.8,
    image: "satinskirt.jpg",
    description: "Elegant satin skirt with a smooth luxurious finish.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Tailored Shorts",
    category: "bottoms",
    price: 79.99,
    rating: 4.6,
    image: "tailoredshorts.jpg",
    description: "Smart tailored shorts with a clean modern finish.",
    isNew: false,
    isSale: true,
    discount: 15,
    stock: 10,
  },
  {
    name: "Wide Pants",
    category: "bottoms",
    price: 119.99,
    rating: 4.8,
    image: "widepants.jpg",
    description: "Comfortable wide-leg pants with an elegant silhouette.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Asoke Skirt",
    category: "bottoms",
    price: 139.99,
    rating: 4.8,
    image: "asokesk.jpg",
    description: "Beautiful Asoke-inspired skirt with a stylish design.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },

  // =========================
  // ACCESSORIES
  // =========================
  {
    name: "Arm Cuff",
    category: "accessories",
    price: 49.99,
    rating: 4.8,
    image: "armcuff.jpg",
    description: "Elegant arm cuff accessory for a luxurious finishing touch.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Bangle",
    category: "accessories",
    price: 39.99,
    rating: 4.7,
    image: "bangle.jpg",
    description: "Elegant bangle designed to complement any outfit.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Bracelet",
    category: "accessories",
    price: 44.99,
    rating: 4.8,
    image: "bracelet.jpg",
    description: "Stylish bracelet for an elegant everyday look.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Glasses",
    category: "accessories",
    price: 89.99,
    rating: 4.8,
    image: "glasses.jpg",
    description: "Stylish glasses that add a fashionable finishing touch.",
    isNew: false,
    isSale: true,
    discount: 20,
    stock: 10,
  },
  {
    name: "Gold Belt",
    category: "accessories",
    price: 59.99,
    rating: 4.7,
    image: "goldbelt.jpg",
    description: "Elegant gold belt for a luxurious fashion statement.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Hair Clips",
    category: "accessories",
    price: 29.99,
    rating: 4.6,
    image: "hairclips.jpg",
    description: "Beautiful hair clips for a stylish finishing touch.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Jewelry Set",
    category: "accessories",
    price: 149.99,
    rating: 4.9,
    image: "jewelryset.jpg",
    description: "Elegant jewelry set designed for special occasions.",
    isNew: true,
    isSale: true,
    discount: 15,
    stock: 10,
  },
  {
    name: "Necklace",
    category: "accessories",
    price: 79.99,
    rating: 4.8,
    image: "necklace.jpg",
    description: "Elegant necklace that adds a luxurious finishing touch.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Ribbon",
    category: "accessories",
    price: 24.99,
    rating: 4.6,
    image: "ribbon.jpg",
    description: "Simple and stylish ribbon accessory.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Hair Accessory",
    category: "accessories",
    price: 34.99,
    rating: 4.7,
    image: "hairclips.jpg",
    description: "Stylish hair accessory for completing your look.",
    isNew: true,
    isSale: false,
    discount: 0,
    stock: 10,
  },
  {
    name: "Fashion Accessory",
    category: "accessories",
    price: 69.99,
    rating: 4.7,
    image: "asokesk.jpg",
    description: "Fashion accessory for a stylish and elegant look.",
    isNew: false,
    isSale: false,
    discount: 0,
    stock: 10,
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB connected.");

    await Product.deleteMany({});

    console.log("Old products cleared.");

    const createdProducts = await Product.insertMany(products);

    console.log(
      `Successfully added ${createdProducts.length} products to MongoDB.`
    );

    await mongoose.connection.close();

    console.log("MongoDB connection closed.");

    process.exit(0);
  } catch (error) {
    console.error("Error seeding products:", error);

    await mongoose.connection.close();

    process.exit(1);
  }
};

seedProducts();